CREATE TABLE pasts (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(200) NOT FULL,
    content TEXT NOT FULL,
    author VARCHAR NOT FULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    updated_at TIMESTAMP DEFAULT CURRENT TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);